name = "GBModels"
uuid = "a21a2f6e-06ad-4936-9990-fa46b058b9d4"
authors = ["jeffersonparil@gmail.com"]
version = "1.0.0-DEV"

[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GBCore = "50d95318-1838-4cfa-a614-3543b4bb0509"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
TuringBenchmarking = "0db1332d-5c25-4deb-809f-459bc696f94f"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[sources.GBCore]
rev = "main"
url = "https://github.com/GenomicBreeding/GBCore.jl"

[compat]
AMDGPU = "1.2.3"
BenchmarkTools = "1.6.0"
DataFrames = "1.7.0"
Dates = "1.11.0"
Distances = "0.10.12"
Distributions = "0.25.116"
Documenter = "1.8.0"
GBCore = "1.0.0"
GLMNet = "0.7.4"
LinearAlgebra = "1.11.0"
Lux = "1.9.0"
LuxCUDA = "0.3.3"
MixedModels = "4.29.1"
MultivariateStats = "0.10.3"
Optim = "1.11.0"
Optimisers = "0.4.5"
Optimization = "4.0.5"
Plots = "1.40.9"
ProgressMeter = "1.10.2"
Random = "1.11.0"
ReverseDiff = "1.15.3"
Statistics = "1.11.1"
StatsBase = "0.34.4"
Suppressor = "0.2.8"
Turing = "0.35.5, 0.36, 0.37"
TuringBenchmarking = "0.5.7"
UnicodePlots = "3.7.1"
Zygote = "0.6.75"
julia = "1.11"
oneAPI = "2.0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
